- iterations: 100  # Number of constructions
  construction_method: 'AltBwS'  # AltBwS or AltInS
  parameters:
    distribution: 'Geometric'  # Triangular or Geometric
    beta: -1  # From 0 to 1 // if -1, random selection for each construction
  local_search: 'Dominance'  # Dominance or Alternate
  strategy: 'VND'  # Standard, or VND
  neighborhoods:
    1: [1, 1]
    2: [1, 2]
    3: [2, 1]
  scheme: 'Best'  # Best, or First
