- iterations: 100  # Number of constructions
  # Construction stage
  parameters:
    distribution: 'Geometric'  # Triangular or Geometric
    beta: -1  # From 0 to 1 // if -1, random selection for each construction
  # Local Improvement stage
  strategy: 'VND'  # Standard, or VND
  neighborhoods:
    1: [1, 1]
    2: [1, 2]
    # 3: [2, 1]
  scheme: 'First'  # Best, or First
