- iterations: 100  # Number of constructions
  construction_method: 'AltBwS'  # AltBwS or AltInS
  parameters:
    distribution: 'Geometric'  # Triangular or Geometric
    beta: 0.5  # From 0 to 1
  local_search: 'Dominance'  # Dominance or Alternate
  strategy: 'VND'  # Standard, or VND
  scheme: 'Best'  # Best, or First
