- iterations: 100  # Number of constructions
  # Construction stage
  parameters:
    distribution: 'Geometric'  # Triangular or Geometric
    beta: 0.25  # From 0 to 1 // if -1, random selection for each construction
  # Local Improvement stage
  strategy: 'VND'  # Standard, or VND
  neighborhoods:
    1: [1, 1]
    2: [1, 2]
    3: [2, 1]
  scheme: 'First'  # Fast, or First
  # Limits
  execution_limits:
    max_time: 150  # Maximum execution time for B-GRASP with VND
    max_local_search_time: 2  # Maximum execution time for FiILS without improvements
